### ISSUE TITLE
Implement passthrough extension

### ISSUE THREAD

**Issue by j2kun** [gohugoio/hugo-goldmark-extensions#1]
Continuing from https://github.com/gohugoio/hugo/issues/10894

I'm happy to take a first pass at the implementation

**Comment by jmooring** [comment]
Notes...

1. This is a stand alone implementation, independent of Hugo.
2. Integration with Hugo is the second step, to be implemented as a PR in the Hugo repository.
3. This is probably a good starting point for test cases:

    ```text
    git clone --single-branch -b hugo-github-issue-10894 https://github.com/jmooring/hugo-testing hugo-github-issue-10894
    cd hugo-github-issue-10894
    hugo server
    ```
4. The four delimiter pairs must work on the same line as the pass-through content, or on the preceding/following lines, but not mixed. For example, these shall not be passed-through:

    ```text
    $inline
    $
    
    $$block
    $$
    ```

**Comment by bep** [comment]
My 50 cents. As to the config struct, I think it makes sense to start out with the delimiters @jmooring posted in another thread.

```toml
delimiters:
          - ['$','$']    # inline equations
          - ['$$','$$']  # block equations
          - ['\(','\)']  # inline equations
          - ['\[','\]']  # block equations
```

* I suspect you need/want to split these into block/inline (as the inline/block parsers in Goldmark are two separate things)
* We should add a default HTML renderer for this, but it would also be useful to export whatever new AST kinds (2?) we come up with.

@jmooring if would be great if you could somehow manage this issue, but just shout if you need my attention.

**Comment by jmooring** [comment]
> you could somehow manage this issue

Will do, leaving initial implementation to @j2kun.

**Comment by j2kun** [comment]
> The four delimiter pairs must work on the same line as the pass-through content, or on the preceding/following lines, but not mixed.

Not sure I understand what's being asked for here. May an inline equation be split across lines within a paragraph?

```
This is an example of an inline equation split across lines: $\sum_{x = 3}^10
x^2 = 3x + 5$. Should this be allowed?
```

This seems fine to me, and if so, I don't see why the following wouldn't be feasible (or why the implementation would be any different)

```
This is an example of an inline equation split across lines: $\sum_{x = 3}^10 x^2 = 3x + 5
$. Should this be allowed?
```

**Comment by jmooring** [comment]
> Should this be allowed?

I don't think so, but test against other implementations (GitHub gist, GitLab snippet).

With a GitHub gist this is OK:

```
Inline $x = {-b \pm \sqrt{b^2-4ac} \over 2a}
$ equation
```

But this is not:

```text
Inline $
x = {-b \pm \sqrt{b^2-4ac} \over 2a}$ equation
```

And neither of the above work with GitLab snippets.

Maybe you can find a spec somewhere...

**Comment by jmooring** [comment]
Both "split" examples above work fine with the VS Code markdown preview, so maybe its OK. My concern is false positives, which is why a spec would be great.

**Comment by j2kun** [comment]
My context is all coming from uses of MathJAX, KaTeX, and others in places like mathoverflow.com, math.stackexchange.com, and in normal LaTeX documents, where splitting mathmode across single-line breaks is always accepted (and double-line breaks are not). They also support using "block" mathmode in a paragraph, like

```
Hello I am $$x$$ how are you
```

And this would render the `$$x$$` as its own offset equation, splitting the context line into two paragraphs.

I'm not aware of any standard spec, except LaTeX itself as a reference implementation. My plan is to test against KaTeX or MathJAX as a reference implementation.

**Comment by jmooring** [comment]
> My plan is to test against KaTeX or MathJAX as a reference implementation.

Sounds good. I'm adding some test cases to the repo/branch mentioned above.

**Comment by j2kun** [comment]
I started implementing it, then got confused that the following tests are passing without any extension:

https://github.com/j2kun/hugo-goldmark-extensions/blob/main/passthrough/passthrough_test.go

Any idea why that might be? Do I need to configure the goldmark parser a certain way?

**Comment by jmooring** [comment]
You need to test with LaTeX that is molested when the markdown is converted to HTML. Please look at these test cases:

```
git clone --single-branch -b hugo-github-issue-10894 https://github.com/jmooring/hugo-testing hugo-github-issue-10894
cd hugo-github-issue-10894
hugo server
```
